### ISSUE TITLE
False Positive: spark-core-util.exe is labeled as Trojan by some AV vendors

### ISSUE THREAD

**Issue by Q7ak5** [Neo23x0/Loki#137]
Few days ago two anti-malware engines (Bitdefender and HitmanPro) labeled the current version of spark-core-util.exe as generic trojan (Trojan.GenericKD.32703131). The file showed the SHA256 hash: 9B4D9812D742679F2277D00454E764C3AD2C7511FB8035CA5713F8D226A72B86.

I contacted by e-mail HitmanPro and Bitdefender and asked them to while list the file as false positive. Bitdefender has not reacted so far on my two e-mails sent. However, HitmanPro told me that they have whitlisted it in their engine. However, they told me that other anti-malware engines (not only Bitdefender) still consider this file as malicious.

I checked with an older version, from spark-core-util.exe, this is not affected. But, if I run an update immediately Bitdefender catches the file and delete it. I suggest to check the matter and take steps for whitelisting the application from anti-malware vendors list. At the moment it is not possible to work with an updates version of spark-core.

**Comment by Neo23x0** [comment]
> they told me that other anti-malware engines (not only Bitdefender) still consider this file as malicious

Well, it's not. I'd say it's their fault. 
https://twitter.com/cyb3rops/status/1195321026210664448

**Comment by Q7ak5** [comment]
Bitdefender has not whitelisted it yet. Today, I received an e-mail from Bitdefender to submit the file. I sent it today a third time to them for investigation. No decision made so far by Bitdefender. Still not possible to use spark-core with latest updates.

**Comment by Q7ak5** [comment]
Bitdefender told me today, that it is no virus in the file. Indeed now spark-core-util.exe is not longer listed as trojan. However, in updgade process a temporary file is generated called: new-spark-core-util.exe.tmp this file is now labled as trojan Bitdefender again destroy the spark core installation. I still working with Bitdefender to getting spark core released from their target list. Because I still working there for some weeks and I cannot use spark core, I would appreciate your support as developer in this matter.

**Comment by Neo23x0** [comment]
The reason why this happened is that someone at Bitdefender didn't fix their bad rule but has defined an exclusion via hash. 

The file `new-spark-core-util.exe.tmp` is an updated version of `spark-core-util` that appears temporarily during the update. These new versions contain only minor changes in wording or some additional output messages, but nothing fundamental. We could verify my hypothesis by adding a binary 0 (`0x00`) or any other byte to the `spark-core-util.exe` that they've whitelisted. 

Since we're about to EOL SPARK Core anyway this or next week, I wouldn't put too much effort in Bitdefenders flawed signatures and rather wait and see if the same happens with the new `thor-lite-util.exe`.

**Comment by Q7ak5** [comment]
Finally Bitdefender released spark-core-util.exe from their listing, after many weeks of discussion. Now it is possible to use it again.
