### ISSUE TITLE
False (?) positive on BitTorrent installer

### ISSUE THREAD

**Issue by mgdde** [Neo23x0/Loki#17]
The free BitTorrent Installer as can be downloaded from http://www.bittorrent.com/downloads/complete/track/stable/os/win/ creates a match:

[INFO] Scanning c:\ftp\bittorrent ...
[WARNING] Yara Rule MATCH: Base64_encoded_Executable DESCRIPTION: Detects an base64 encoded executable (often embedded)
FILE: c:\ftp\bittorrent\BitTorrent-7.9.1.exe
MD5: c355b539c02e2def2946af0528d2959d
SHA1: d35cb873c92ac2ea28a5246c9b11af1d13a4021b
SHA256: 6bb4a854428c3e6c6be486b7870759699f4db7e9bd9c8f5b8db120dd3356291b
MATCHES: Str1: TVoAAAAAAAAAAAAAAAAAAAAAAAA
[WARNING] Yara Rule MATCH: Base64_encoded_Executable DESCRIPTION: Detects an base64 encoded executable (often embedded)
FILE: c:\ftp\bittorrent\BitTorrent-7.9.3.exe
MD5: ab25777de5188e05fcc19d3b3162d494
SHA1: 6c97c9ce8cb57b16db6e5d7d6cc92394990b879a
SHA256: a15f308854e46e274a093284a991a73cebab185549b48f4d6d2c3c824a82d229
MATCHES: Str1: TVoAAAAAAAAAAAAAAAAAAAAAAAA
[RESULT] Suspicious objects detected!
[RESULT] Loki recommends a deeper analysis of the suspicious objects.

Kind regards,
Michael

**Comment by Neo23x0** [comment]
Hi Michael. 

LOKI is not meant to be an Antivirus alternative. 
It does not modify, delete or clean objects on disk.
I intentionally designed it to be more verbose and report "suspicious" elements. This is something an Antivirus can not do, as it works independently and has to decide between "black" and "white" in order to delete or clean the element. 

"One could be tempted to believe that I wrote this article in order to degrade Antivirus engines, but this isn’t the case. Antivirus solutions are still play a key role and carry the heavy burden of definite detection. Their scan result has to be „thumbs up“ or „thumbs down“ as there is no middle ground.

Years ago they introduced signatures to detect „Potentially Unwanted Applications“ (PUA). Users or administrators decide on what to do if one of these „dual use“ tools has been found on a system. Handling thousands of the events generated by the Antivirus agents is a difficult task, even with a central console or SIEM integrated log files. It is easy to understand why PUA events do not play an important role in view of dozens of Trojan detections per day."

https://www.bsk-consulting.de/2015/03/10/apt-detection-is-about-metadata/

I would like to leave the rule in the rule base.
The file does contain a base64 encoded executable, which is very suspicious and should be reviewed by the users (home env) or security analyst (corporate env).
