### ISSUE TITLE
Loki.exe removed by window defender

### ISSUE THREAD

**Issue by GREEKYnikhilsharma** [Neo23x0/Loki#85]
Why window defender is removing a Simple scanner?

**Comment by GREEKYnikhilsharma** [comment]
window defender detected Trojan:Win32/Azden.A!cl in loki.exe and Trojan:Java/Micuh in test\yara\JFolder.jsp

**Comment by vwhissell** [comment]
False Positive. Just create an exception in Windows Defender for: File -> Loki.exe

**Comment by GREEKYnikhilsharma** [comment]
Thanks man but i Am looking for a way to make it  undetectable - as the same functionality can be legitimately  mirrored by any other executable file , but one thing why it is getting caught by antivirus as it only traverses directories and  processes - scans for regular expressions match (simple search) and Loki.exe is just executable of Loki.py it needs other python and signature file to function. If window defender is detecting by hash signature then just minor changes can change the hash.

**Comment by vwhissell** [comment]
And Now, Microsoft Endpoint Protection Reports it as infected.

Seriously, Microsoft is sooooooooo crap. Are they doing this on purpose? Worst "IT Security" Team Ever. Who is the CISO of Microsoft? I would, ANYTIME, fire that guy. Windows Subsystem for Linux = no security, their AV Product sucks ass, Windows is not secure (Can't follow best practices with Sandboxing and stuff? Is it that hard?), Azure, very bad security, ... and many many many more.

Yep, this morning, I'm pissed. At least, because or their suits, we got a job. Continue being crap Windows, you will give us jobs! :)

**Comment by Hodgegoblin** [comment]
Sophos is now reporting loki.exe as Troj/Agent-AXXR. Details here: https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/Troj~Agent-AXXR/detailed-analysis.aspx

**Comment by Hodgegoblin** [comment]
Release 0.26.0 was not identified by Sophos as a threat.

**Comment by axence** [comment]
Release 0.26.1 was not identified by Microsoft Windows Defender as a threat.

**Comment by Neo23x0** [comment]
Thanks for the updates 👍
